import Footer from "@/Components/Footer";
import Header from "@/Components/Headers";
import { getSettingQuery } from "@/lib/sanityFetch";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pageData = await getSettingQuery();

  const headerData = pageData?.header || {
    logo: { image: { asset: null } },
    navItem: { navItem: [] },
  };

  const footerData = pageData?.footer || {
    logo: { image: { asset: null } },
    footerLinks: { navItem: [] },
    socialLinks: [],
    contactInfo: { email: "", phone: "", address: "" },
    footerText: "",
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header data={headerData} />
        {children}
        <Footer data={footerData} />
      </body>
    </html>
  );
}
